exchange:
  trade:
    name: peatio.trade
    type: headers
  notification:
    name: peatio.notification
    type: direct
  orderbook:
    name: peatio.orderbook
    type: fanout
  events:
    name: peatio.events
    type: direct
  matching:
    name: peatio.matching
    type: direct

queue:
  matching:
    name: peatio.matching
    durable: true
  new_trade:
    name: peatio.trade.new
    durable: true
  order_processor:
    name: peatio.order.processor
    durable: true
  depth_cache:
    name: peatio.depth.cache
    durable: true
  market_ticker:
    name: peatio.trade.market_ticker
    durable: false
  withdraw_coin:
    name: peatio.withdraw.coin
    durable: false
  deposit_collection_fees:
    name: peatio.deposit.collection_fees
    durable: false
  deposit_collection:
    name: peatio.deposit.collection
    durable: false
  deposit_coin_address:
    name: peatio.deposit.coin.address
    durable: true
  influx_writer:
    name: peatio.trade.writer
    durable: false
  trade_error:
    name: peatio.trades.errors
    durable: false
  events_processor:
    name: peatio.events.processor
    durable: false

binding:
  matching:
    queue: matching
    clean_start: true
    exchange: matching
  trade_executor:
    queue: new_trade
    exchange: matching
  order_processor:
    queue: order_processor
    exchange: matching
  withdraw_coin:
    queue: withdraw_coin
  deposit_coin_address:
    queue: deposit_coin_address
  influx_writer:
    queue: influx_writer
    exchange: trade
  trade_error:
    queue: trade_error
    exchange: matching
  events_processor:
    queue: events_processor
    exchange: events
  depth_cache:
    queue: depth_cache
    exchange: matching

channel:
  trade_executor:
    prefetch: 5
  order_processor:
    prefetch: 5
